In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer

In [ ]:
data = pd.read_csv('/content/Placement_Data_Full_Class.csv')


In [ ]:
data.head

<bound method NDFrame.head of      sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech  

In [ ]:
data.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [ ]:
data.shape

(215, 15)

In [ ]:
data.salary=data.salary.fillna('0')

In [ ]:
data.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [ ]:
data=data.drop(columns=['ssc_b','hsc_b','salary'])

In [ ]:
data['gender'].replace('M',0,inplace=True)
data['gender'].replace('F',1,inplace=True)
data['workex'].replace('No',0,inplace=True)
data.workex=data['workex'].replace('Yes',1).replace('No',0) 
data['status'].replace('Not Placed',0,inplace=True)
data['status'].replace('Placed',1,inplace=True)


In [ ]:
data.dtypes

sl_no                       int64
gender                      int64
ssc_p                     float64
hsc_p                     float64
hsc_s                      object
degree_p                  float64
degree_t                   object
workex                      int64
etest_p                   float64
specialisation             object
mba_p                     float64
status                      int64
degree_t_Sci&Tech          object
degree_t_Comm&Mgmt         object
degree_t_Others            object
specialisation_Mkt&HR      object
specialisation_Mkt&Fin     object
dtype: object

In [ ]:
data

sl_no  gender  ssc_p  hsc_p     hsc_s  degree_p   degree_t  workex  \
0        1       0  67.00  91.00  Commerce     58.00   Sci&Tech       0   
1        2       0  79.33  78.33   Science     77.48   Sci&Tech       1   
2        3       0  65.00  68.00      Arts     64.00  Comm&Mgmt       0   
3        4       0  56.00  52.00   Science     52.00   Sci&Tech       0   
4        5       0  85.80  73.60  Commerce     73.30  Comm&Mgmt       0   
..     ...     ...    ...    ...       ...       ...        ...     ...   
210    211       0  80.60  82.00  Commerce     77.60  Comm&Mgmt       0   
211    212       0  58.00  60.00   Science     72.00   Sci&Tech       0   
212    213       0  67.00  67.00  Commerce     73.00  Comm&Mgmt       1   
213    214       1  74.00  66.00  Commerce     58.00  Comm&Mgmt       0   
214    215       0  62.00  58.00   Science     53.00  Comm&Mgmt       0   

     etest_p specialisation  mba_p  status degree_t_Sci&Tech  \
0       55.0         Mkt&HR  58.80       1                 1   
1       86.5        Mkt&Fin  66.28       1                 1   
2       75.0        Mkt&Fin  57.80       1                 0   
3       66.0         Mkt&HR  59.43       0                 1   
4       96.8        Mkt&Fin  55.50       1                 0   
..       ...            ...    ...     ...               ...   
210     91.0        Mkt&Fin  74.49       1                 0   
211     74.0        Mkt&Fin  53.62       1                 1   
212     59.0        Mkt&Fin  69.72       1                 0   
213     70.0         Mkt&HR  60.23       1                 0   
214     89.0         Mkt&HR  60.22       0                 0   

    degree_t_Comm&Mgmt degree_t_Others specialisation_Mkt&HR  \
0                    0               0                     1   
1                    0               0                     0   
2                    1               0                     0   
3                    0               0                     1   
4                    1               0                     0   
..                 ...             ...                   ...   
210                  1               0                     0   
211                  0               0                     0   
212                  1               0                     0   
213                  1               0                     1   
214                  1               0                     1   

    specialisation_Mkt&Fin  
0                        0  
1                        1  
2                        1  
3                        0  
4                        1  
..                     ...  
210                      1  
211                      1  
212                      1  
213                      0  
214                      0  

[215 rows x 17 columns]

In [ ]:
data['degree_t_Sci&Tech']=data['degree_t'].replace('Comm&Mgmt','0').replace('Others','0').replace('Sci&Tech','1')
data['degree_t_Comm&Mgmt']=data['degree_t'].replace('Sci&Tech','0').replace('Others','0').replace('Comm&Mgmt','1')
data['degree_t_Others']=data['degree_t'].replace('Sci&Tech','0').replace('Comm&Mgmt','0').replace('Others','1')
data['specialisation_Mkt&HR']=data['specialisation'].replace('Mkt&Fin','0').replace('Mkt&HR','1')
data['specialisation_Mkt&Fin']=data['specialisation'].replace('Mkt&HR','0').replace('Mkt&Fin','1')

In [ ]:
x = data.iloc[:,0:23]
x

sl_no  gender  ssc_p  hsc_p     hsc_s  degree_p   degree_t  workex  \
0        1       0  67.00  91.00  Commerce     58.00   Sci&Tech       0   
1        2       0  79.33  78.33   Science     77.48   Sci&Tech       1   
2        3       0  65.00  68.00      Arts     64.00  Comm&Mgmt       0   
3        4       0  56.00  52.00   Science     52.00   Sci&Tech       0   
4        5       0  85.80  73.60  Commerce     73.30  Comm&Mgmt       0   
..     ...     ...    ...    ...       ...       ...        ...     ...   
210    211       0  80.60  82.00  Commerce     77.60  Comm&Mgmt       0   
211    212       0  58.00  60.00   Science     72.00   Sci&Tech       0   
212    213       0  67.00  67.00  Commerce     73.00  Comm&Mgmt       1   
213    214       1  74.00  66.00  Commerce     58.00  Comm&Mgmt       0   
214    215       0  62.00  58.00   Science     53.00  Comm&Mgmt       0   

     etest_p specialisation  mba_p  status degree_t_Sci&Tech  \
0       55.0         Mkt&HR  58.80       1                 1   
1       86.5        Mkt&Fin  66.28       1                 1   
2       75.0        Mkt&Fin  57.80       1                 0   
3       66.0         Mkt&HR  59.43       0                 1   
4       96.8        Mkt&Fin  55.50       1                 0   
..       ...            ...    ...     ...               ...   
210     91.0        Mkt&Fin  74.49       1                 0   
211     74.0        Mkt&Fin  53.62       1                 1   
212     59.0        Mkt&Fin  69.72       1                 0   
213     70.0         Mkt&HR  60.23       1                 0   
214     89.0         Mkt&HR  60.22       0                 0   

    degree_t_Comm&Mgmt degree_t_Others specialisation_Mkt&HR  \
0                    0               0                     1   
1                    0               0                     0   
2                    1               0                     0   
3                    0               0                     1   
4                    1               0                     0   
..                 ...             ...                   ...   
210                  1               0                     0   
211                  0               0                     0   
212                  1               0                     0   
213                  1               0                     1   
214                  1               0                     1   

    specialisation_Mkt&Fin  
0                        0  
1                        1  
2                        1  
3                        0  
4                        1  
..                     ...  
210                      1  
211                      1  
212                      1  
213                      0  
214                      0  

[215 rows x 17 columns]

In [ ]:
x=data.drop(columns=['status','hsc_s','degree_t','specialisation'])
x.head()

sl_no  gender  ssc_p  hsc_p  degree_p  workex  etest_p  mba_p  \
0      1       0  67.00  91.00     58.00       0     55.0  58.80   
1      2       0  79.33  78.33     77.48       1     86.5  66.28   
2      3       0  65.00  68.00     64.00       0     75.0  57.80   
3      4       0  56.00  52.00     52.00       0     66.0  59.43   
4      5       0  85.80  73.60     73.30       0     96.8  55.50   

  degree_t_Sci&Tech degree_t_Comm&Mgmt degree_t_Others specialisation_Mkt&HR  \
0                 1                  0               0                     1   
1                 1                  0               0                     0   
2                 0                  1               0                     0   
3                 1                  0               0                     1   
4                 0                  1               0                     0   

  specialisation_Mkt&Fin  
0                      0  
1                      1  
2                      1  
3                      0  
4                      1

In [ ]:
temp = [565, 1, 80.00, 78.00,87.00,1,55.0,56.00,1,0,0,0,0]


In [ ]:
y = data['status']
y

0      1
1      1
2      1
3      0
4      1
      ..
210    1
211    1
212    1
213    1
214    0
Name: status, Length: 215, dtype: int64

In [ ]:
x.iloc[:,12].unique()

array(['0', '1'], dtype=object)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=.4, random_state=10)

In [ ]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(129, 13) (129,) (86, 13) (86,)


**Logistic Regression**

In [ ]:
lr = LogisticRegression(random_state=0)
lr.fit(X_train,y_train)
print("Training Acc: ",lr.score(X_train,y_train))
print("Testing Acc: ",accuracy_score(y_test, lr.predict(X_test)))

Training Acc:  0.8914728682170543
Testing Acc:  0.813953488372093


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [ ]:
lr.predict(X_test)

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1])

In [ ]:
lr.predict([temp])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1])

**Decision Tree**

In [ ]:
dct = DecisionTreeClassifier(random_state=0,max_depth=4)
%time dct.fit(X_train,y_train)
print("Training Acc: ",accuracy_score(y_train,dct.predict(X_train)))
print("Testing Acc: ",accuracy_score(y_test, dct.predict(X_test)))

CPU times: user 5.55 ms, sys: 0 ns, total: 5.55 ms
Wall time: 5.26 ms
Training Acc:  0.9147286821705426
Testing Acc:  0.7441860465116279


In [ ]:
dct.predict(X_test)

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
dct.predict([temp])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])